
export const data = [
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "success",
    },
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "pending",
    },
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "fail",
    },
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "collected",
    },
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "success",
    },
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "pending",
    },
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "fail",
    },
    {
      img: "src/assets/123.jpg",
      title: "Cy Ganderton",
      description: "Quality Control Specialist",
      points: "50 pts",
      status: "collected",
    },
    {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "success",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "pending",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "fail",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "collected",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "success",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "pending",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "fail",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "collected",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "success",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "pending",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "fail",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "collected",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "success",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "pending",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "fail",
      },
      {
        img: "src/assets/123.jpg",
        title: "Cy Ganderton",
        description: "Quality Control Specialist",
        points: "50 pts",
        status: "collected",
      },
  ];